# Generated by Django 2.1.2 on 2018-10-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
