# Generated by Django 2.1.2 on 2018-10-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoting_app', '0002_auto_20181015_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
