# Generated by Django 2.1.2 on 2018-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoting_app', '0003_auto_20181015_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='pass', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
