# Generated by Django 2.1.2 on 2018-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoting_app', '0005_auto_20181023_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
