# Generated by Django 2.1.2 on 2018-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoting_app', '0007_auto_20181023_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
